#!/bin/sh

GREEN="\033[1;32m"
RESET="\033[0m"

# Mount essential filesystems
echo "[*] Mounting essential filesystems"
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

# Set up PATH
echo "[*] Setting up PATH"
export PATH=/bin

# Launch installer
exec /bin/install
